server:
  port: 9191

spring:
  application:
    name: API-GATWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"  
      routes:
      - id: NFTS-SERVICE 
        uri: : http://localhost:8081/ 
        predicates:
        - Path=/nft/** 
      - id: TRANSACTION-SERVICE 
        uri: : http://localhost:8082/ 
        predicates:
        - Path=/transaction/** 
      


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost